import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Companio — Trusted. Verified. Companionship.',
    short_name: 'Companio',
    description:
      'Book ID-verified companions for city guiding, events, gym sessions, and real conversation — strictly platonic, always safe.',
    start_url: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#FBFCFF',
    theme_color: '#2E6BFF',
    icons: [
      // Maskable icons (Android adaptive shapes) — generated by scripts/gen-icons.mjs.
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      // A plain "any" icon for launchers that don't apply a mask.
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/favicon.ico', sizes: 'any', type: 'image/x-icon' },
    ],
    categories: ['lifestyle', 'social'],
  }
}
