import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Companio — Trusted. Verified. Companionship.',
    short_name: 'Companio',
    description:
      'Book ID-verified companions for city guiding, events, gym sessions, and real conversation — strictly platonic, always safe.',
    start_url: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#FBFCFF',
    theme_color: '#2E6BFF',
    // All generated by scripts/gen-icons.mjs from the Seal (components/ui/Seal.tsx),
    // so the installed app, the tab and the nav are the same mark.
    icons: [
      // Maskable: full-bleed gradient, heart inside the safe zone, because
      // Android crops these to its own adaptive shape.
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      // "any" is for launchers that apply NO mask, so it must be the round seal.
      // This pointed at the maskable file, which meant those launchers showed a
      // square — the one shape the logo has never been.
      { src: '/icon-any-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/favicon.ico', sizes: '16x16 32x32 48x48', type: 'image/x-icon' },
    ],
    categories: ['lifestyle', 'social'],
  }
}
